name: bus-zeiterfassung

services:
  app:
    build: .
    container_name: bus-zeiterfassung
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
